version: '2'
services:
    jhflow-app:
        image: jhflow
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhflow-postgresql:5432/jhflow
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhflow-postgresql:
        extends:
            file: postgresql.yml
            service: jhflow-postgresql
